/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Staking } from "../Staking";

export class Staking__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Staking {
    return new Contract(address, _abi, signerOrProvider) as Staking;
  }
}

const _abi = [
  {
    inputs: [],
    name: "purge_keys",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "register_as_candidate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "keys",
        type: "bytes",
      },
    ],
    name: "set_keys",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
